In [1]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup as soup
import json

In [2]:
with open('chicago_filter.json', 'r') as f:
    data = json.load(f)
df = pd.DataFrame(data)

In [3]:
data[0]

{'industryName': 'Computer Software',
 'lastName': 'Zhang',
 'student': False,
 'geoCountryName': 'United States',
 'geoCountryUrn': 'urn:li:fs_geo:103644278',
 'geoLocationBackfilled': False,
 'elt': False,
 'industryUrn': 'urn:li:fs_industry:4',
 'firstName': 'Elaine',
 'entityUrn': 'urn:li:fs_profile:ACoAAAmxZp8Bw7PhHswXpaNq8x55z7YZWbGs1b4',
 'geoLocation': {'geoUrn': 'urn:li:fs_geo:103112676'},
 'geoLocationName': 'Chicago, Illinois',
 'location': {'basicLocation': {'countryCode': 'us'}},
 'headline': 'MBA Candidate at The University of Chicago Booth School of Business',
 'displayPictureUrl': 'https://media-exp1.licdn.com/dms/image/C4E03AQGaqhwyj12zNw/profile-displayphoto-shrink_',
 'img_100_100': '100_100/0/1597435547761?e=1633564800&v=beta&t=C2f5cW4Qj2sKSIR9P2VAfeNpag5JEO0EB128tOeUy3w',
 'img_200_200': '200_200/0/1597435547761?e=1633564800&v=beta&t=LL1gwyrPbu4dE5RTMwYWDPrSKFFvqMSvX6Czztx0A1k',
 'img_400_400': '400_400/0/1597435547761?e=1633564800&v=beta&t=Df_WqQazpLmhMgj1vVXlRUV5

In [4]:
data[1]

{'industryName': 'Banking',
 'lastName': 'XU',
 'locationName': 'Hong Kong',
 'student': False,
 'geoCountryName': 'Hong Kong SAR',
 'geoCountryUrn': 'urn:li:fs_geo:103291313',
 'geoLocationBackfilled': False,
 'elt': True,
 'industryUrn': 'urn:li:fs_industry:41',
 'firstName': 'Yidong (Jason)',
 'entityUrn': 'urn:li:fs_profile:ACoAACApXbMBPPARPoVUsrwGdQPy7YUiU6-KBco',
 'geoLocation': {'geoUrn': 'urn:li:fs_geo:103291313'},
 'location': {'basicLocation': {'countryCode': 'hk'}},
 'headline': 'M.S. in Financial Mathematics at the University of Chicago',
 'displayPictureUrl': 'https://media-exp1.licdn.com/dms/image/C4E03AQF9Byyy2V8wGA/profile-displayphoto-shrink_',
 'img_100_100': '100_100/0/1567067924579?e=1633564800&v=beta&t=1p15ylvVTNG2oBou0mMmoIq8ORxvTCbdAOcmR5JT_KE',
 'img_200_200': '200_200/0/1567067924579?e=1633564800&v=beta&t=VVyXJLJbaUKAnljwQV59WKUAu_LehtZOh4oEMNyaHtI',
 'img_400_400': '400_400/0/1567067924579?e=1633564800&v=beta&t=OT6Mp5F15kLN1e3m_0IyLWJ3xuGvxSI2JTqJHiuNtn0',
 'i

In [5]:
data[2]

{'industryName': 'Investment Banking/Venture',
 'lastName': 'Ngai',
 'student': False,
 'geoCountryName': 'Hong Kong SAR',
 'geoCountryUrn': 'urn:li:fs_geo:103291313',
 'geoLocationBackfilled': False,
 'elt': True,
 'industryUrn': 'urn:li:fs_industry:45',
 'firstName': 'Elvis',
 'entityUrn': 'urn:li:fs_profile:ACoAAB2QNFQBb9_CuNReCkYUn8rQmXLiKVD4-FQ',
 'geoLocation': {'geoUrn': 'urn:li:fs_geo:102817007'},
 'geoLocationName': 'Hong Kong',
 'location': {'basicLocation': {'countryCode': 'hk'}},
 'headline': 'Investment Banking Analyst at CICC',
 'profile_id': 'ACoAAB2QNFQBb9_CuNReCkYUn8rQmXLiKVD4-FQ',
 'profile_urn': 'urn:li:fs_miniProfile:ACoAAB2QNFQBb9_CuNReCkYUn8rQmXLiKVD4-FQ',
 'member_urn': 'urn:li:member:495989844',
 'experience': [{'locationName': 'Hong Kong SAR',
   'entityUrn': 'urn:li:fs_position:(ACoAAB2QNFQBb9_CuNReCkYUn8rQmXLiKVD4-FQ,1634878879)',
   'geoLocationName': 'Hong Kong SAR',
   'geoUrn': 'urn:li:fs_geo:103291313',
   'companyName': 'CICC',
   'timePeriod': {'startD

In [8]:
urn =[]
for k in range(len(data)):
    urn.append(data[k]['member_urn'])

In [9]:
data = pd.DataFrame(urn)

In [24]:
data[0].str.replace(r'\D', '').astype(int).drop_duplicates().shape[0]

<ipython-input-24-fb6f4c933598>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  data[0].str.replace(r'\D', '').astype(int).drop_duplicates().shape[0]


656

In [19]:
data.drop_duplicates().shape[0]

656

In [ ]:
und_name = []
und_syear = []
und_eyear = []
lname = []
fname = []

for i in range(len(data)): 
    #print(i['education'][0]['timePeriod']['endDate']['year']) 
   
    for k in range(len(data[i]['education'])):
        try:
             #und_name.append(data[i]['education'][0]['degreeName'])
             #und_syear.append(data[i]['education'][0]['timePeriod']['startDate']['year'])
             if ('The University of Chicago' in und_eyear.append(data[i]['education'][k]['schollName'])) and ():
                fname.append(data[i]['firstName'])
                lname.append(data[i]['lastName'])
                data[i]['education'][0]['timePeriod']['endDate']['year'])
        except KeyError:
             und_eyear.append('')
            #print(f"s age is unknown.")


            #und_syear(2021) 
           

In [4]:
a = []
for i in range(len(data)):
    try:
        a.append(data[i]['industryName'])
    except KeyError:
        print('No')

No
No
No
No
No
No
No
No
No


In [6]:
df22 = pd.DataFrame(a)
df22[0].unique()

array(['Computer Software', 'Banking', 'Investment Banking/Venture',
       'Management Consulting', 'Insurance', 'Financial Services',
       'Information Technology & Services', 'Internet',
       'Higher Education', 'Research', 'Venture Capital',
       'Investment Management', 'Biotechnology', 'Museums & Institutions',
       'Public Policy', 'International Affairs', 'Education Management',
       'Writing & Editing', 'Hospital & Health Care', 'Law Practice',
       'Computer & Network Security', 'Capital Markets', 'Real Estate',
       'Retail', 'Market Research', 'Nonprofit Organization Management',
       'International Trade & Development',
       'Electrical & Electronic Manufacturing', 'Oil & Energy',
       'Consumer Services', 'Information Services', 'Pharmaceuticals',
       'Legal Services', 'Marketing & Advertising',
       'Staffing & Recruiting', 'Consumer Goods',
       'Government Administration', 'Fine Art', 'Food & Beverages',
       'Import & Export', 'Entertainme

In [19]:
for i in range(len(data)):
    try:
         if data[i]['industryName']=="Investment Banking/Venture":
                print(data[i]['firstName'], data[i]['lastName'],", data[num]:",i)
    except KeyError:
        print('')
   

Elvis Ngai , data[num]: 2

Chris (Weiwen) Ju , data[num]: 6
Olivia Chen , data[num]: 14

Joey Leung , data[num]: 44
Matthew (Kang Seok) Oh , data[num]: 53

Rachel Li , data[num]: 56
Samuel Thong , data[num]: 62


Joshua Lam , data[num]: 86

Yukun Zhang , data[num]: 105
Alexander Weng , data[num]: 110

Sky Gong , data[num]: 152
Cindy Z. , data[num]: 154
Shihting Xu , data[num]: 155
Alessandro R. , data[num]: 161
Clara Wu , data[num]: 162

Joe Lai, CFA , data[num]: 191
Tina Hanting Li , data[num]: 195
Justin Zhang , data[num]: 208
Adrian Ma , data[num]: 213
Patrick Kaye , data[num]: 256
Key, Shangyi Li , data[num]: 276
Yuming He , data[num]: 282
Hailei Lu, CPA , data[num]: 319
Eric Xinpei TANG , data[num]: 330
Vivian Xu , data[num]: 338
Iris Zhang , data[num]: 344
Michael Pang , data[num]: 361
Claire Zhang , data[num]: 373
Christopher Li , data[num]: 379
Ting Peng , data[num]: 410
Xiaoxin (Cathy) Wen , data[num]: 418

Hang Yin , data[num]: 449
Zhaoqing (Felicia) Li , data[num]: 501
Chris

In [1]:
p = 0.512813**40 *0.487187**40 

In [3]:
import math
fact = math.factorial(80)/(math.factorial(40)**2)

In [4]:
result = p*fact

In [5]:
result

0.08662161555400996

In [12]:
res = 0
for i in range(41,80):
    res += (math.factorial(80)/(math.factorial(i)*math.factorial(80-i)))*(0.512813**i) * (0.487187**(80-i))
res

0.5470714306723669

In [4]:
A = np.array([[1, -1,1], [1, 1, 1], [4, 2, 1],[9, 3, 1],[25, 5, 1]])
A_plus =np.linalg.pinv(A)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [7]:
A_plus

array([[ 0.05952381, -0.03571429, -0.04761905, -0.03571429,  0.05952381],
       [-0.38809524,  0.09285714,  0.19047619,  0.19285714, -0.08809524],
       [ 0.5       ,  0.3       ,  0.2       ,  0.1       , -0.1       ]])

In [5]:
A_plus.dot(A)

array([[ 1.00000000e+00, -4.85722573e-17,  2.77555756e-17],
       [ 4.16333634e-16,  1.00000000e+00, -3.60822483e-16],
       [ 1.63757896e-15,  1.94289029e-16,  1.00000000e+00]])

In [14]:
y = np.array([2,1,1,0,3])
res = A_plus.dot(y)

<IPython.core.display.Javascript object>

In [34]:
res

array([ 0.21428571, -0.75714286,  1.2       ])

In [33]:
res[0] - res[1] + res[2]

2.1714285714285735

In [32]:
res[0] +res[1] + res[2]

0.6571428571428584

In [31]:
4*res[0]+2*res[1]+res[2]

0.5428571428571438

In [30]:
9*res[0]+3*res[1]+res[2]

0.8571428571428581

In [29]:
25*res[0]+5*res[1]+res[2]

2.771428571428572

In [46]:
(-(1+math.sqrt(5)))/(math.sqrt(2*math.sqrt(5)+10))

-0.85065080835204

In [45]:
import math

In [48]:
a =5
b =45
c = b/a
b=55
print(c)

9.0


In [7]:
print(len('ababa')/len('ab'))

2.5


In [50]:
a = [1,2,3]
b=a
c= [1,2,3]
print(a==b)
print(a is b)
print(a==c)
print(a is c)

True
True
True
False


In [1]:
7%2

1

In [2]:
new_cpc =1

In [8]:
x='34'
y='15'
print(type(x*5))

<class 'str'>


In [10]:
months = ['январь', 'февраль', 'март', 'апрель', 'май', 'июнь', 'июль', 'август', 'сентябрь', 'октябрь', 'ноябрь', 'декабрь']
months[2:5]

['март', 'апрель', 'май']

In [11]:
campaign = 'yandex_cpc_bmv_brand_summer'
campaign.split('_')[2]

'bmv'

In [12]:
total_costs = { 'google': 1319, 'yandex': 1818, 'promo': 1181 }
sorted( total_costs.keys(), reverse = True )

['yandex', 'promo', 'google']

In [14]:
d = lambda p:p*2
t =lambda p:p*3
x=2
x=d(x)
x=t(x)
x=d(x)
print(x)

24


In [15]:
f=5
a=12
b=a
f==(a-b)

False

In [16]:
a=4 
for i in range(4):
    a+=a

In [17]:
a

64

In [20]:
pip install reports

  Created wheel for reports: filename=reports-0.4.1-py3-none-any.whl size=132328 sha256=27531b31a03cc852fb11f20e07062a2d8e7a9989a014240b2348d460df290e39
  Stored in directory: c:\users\abylk\appdata\local\pip\cache\wheels\e5\8e\73\e0793f46ef923c6623b0e57ebb094004a83026416355b527dc
  Created wheel for easydev: filename=easydev-0.12.0-py3-none-any.whl size=64220 sha256=62a2699724702514dad4065f52a776747218c997db5743321b1e9129f4a56528
  Stored in directory: c:\users\abylk\appdata\local\pip\cache\wheels\e2\47\9f\de01f291cfde341b33383bcf1292b17d64c700d4a12b318a7d
  Created wheel for colormap: filename=colormap-1.0.3-py3-none-any.whl size=15565 sha256=809f760846c48e95831ec6244401d7eff8cfd0a125e7e1a11466fa3ec6ba8858
  Stored in directory: c:\users\abylk\appdata\local\pip\cache\wheels\fd\c1\44\c67a624db335e7ab225d427399f7090caa9bab621875f8203b
Successfully built reports easydev colormap
Note: you may need to restart the kernel to use updated packages.


In [21]:
def add(a,b):
    return a+b
add(a=1,b=3)
    

4

In [22]:
class Reports:
    def __init__(self,start,end):
        self.start =start
        self.end = end
    def correct_dates(self):
        if self.start>self.end:
            return False
        return True
start = '2017-12-25'
end ='2018-01-31'
rep = Reports(start,end)
rep.start='2018-07-01'
print(start,rep.correct_dates())

2017-12-25 False


In [1]:
print(len('ababa')/len('ab'))

2.5


In [4]:
def caapa(c=1,b):
    return c+b
caapa(4)

SyntaxError: non-default argument follows default argument (<ipython-input-4-e9711ea3cff2>, line 1)

In [11]:
def generate_report(url='https://api.local', **kwargs):
    return url 

In [12]:
generate_report(start='2018-07-01', end='2018-07-31')

'https://api.local'

In [13]:
generate_report(start='2018-07-01', end='2018-07-31', url='https://api.local')

'https://api.local'

In [7]:
class Stack(object):
 
    def __init__(self):
        self.stack = []
        
    def __str__(self):
        return ' '.join([str(i) for i in self.stack])
 
    def top(self):
        return self.stack[-1]
 
    def push(self, x):
        ans = -1
        
        return ans
 
    def pop(self):
        self.stack.pop()
 
    def empty(self):
        return len(self.stack) == 0
 
    def size(self):
        return len(self.stack)
 
stack = Stack()
n = int(input())
a = list(map(int, input().split()))
ans = []
for x in a:
    ans.append(stack.push(x))
print(*ans)

5
3 2 5 1
-1 -1 -1 -1


In [1]:
a = [0,1,2,3]
for a[0] in a:
    print(a[0])

0
1
2
3


In [2]:
print('abcd'.translate({'a':'1','b':'2','c':'3','d':'4'}))

abcd
