In [2]:
import numpy as np

In [10]:
a1=np.arange(10)# creates a range from 0 to 9

In [11]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
a2=np.arange(0,9,2)# creates a range from 0 to 9, step 2

In [13]:
print(a2)

[0 2 4 6 8]


In [14]:
a3=np.zeros(5)# create an array with all 0s

In [15]:
print(a3)

[0. 0. 0. 0. 0.]


In [16]:
print(a3.shape)

(5,)


In [19]:
a4=np.zeros((2,3))# array of rank 2 with all 0s; 2 rows and 3

In [21]:
print(a4,a4.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)


In [22]:
a5=np.full(5,8)

In [23]:
print(a5,a5.shape)

[8 8 8 8 8] (5,)


In [24]:
a5=np.full((2,3),8)# array of rank 2 with all 8s

In [25]:
print(a5,a5.shape)

[[8 8 8]
 [8 8 8]] (2, 3)


In [26]:
a6=np.eye(4)# 4x4 identity matrix
print(a6,a6.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)


In [28]:
a7=np.random.random((2,4))# rank 2 array (2 rows 4 columns) with
# random values
# in the half-open interval [0.0, 1.0)
print(a7,a7.shape)

[[0.79176346 0.20145565 0.31014799 0.59695799]
 [0.17544371 0.25532148 0.97775626 0.71802565]] (2, 4)


In [30]:
list1=[1,2,'hey',4]
a8=np.array(list1)
print(a8,a8.shape)

['1' '2' 'hey' '4'] (4,)


In [37]:
print(a8[:3])# row 1 to 3 (not inclusive)

['1' '2' 'hey']


In [49]:
list1=[1,4,2,5]
list2=[2,3,5,6,]
a9=np.array([list1,list2])
print(a9,a9.shape)
print(a9[1][1])

[[1 4 2 5]
 [2 3 5 6]] (2, 4)
3


In [57]:
r1=[1,3,4,12]
r2=np.array(r1)
print(r2[[1,2]])

[3 4]


In [58]:
print(r1>a9)

[[False False  True  True]
 [False False False  True]]


In [60]:
print(r2[r2<2])

[1]


In [61]:
n=np.arange(20)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [121]:
a = np.array([[1,2,3,4,5],
[4,5,6,7,8],
[9,8,7,6,5]])
print(a,'\n')
print(a[0:2,3:],'\n')
print(a[-2,:-3],'\n')
a[1][1]=88
print(a,'\n')
print(a[2:,:],'\n') #all elements form the 2nd column and onwards
a=a.reshape(1,-1)
print(a,'\n')

[[1 2 3 4 5]
 [4 5 6 7 8]
 [9 8 7 6 5]] 

[[4 5]
 [7 8]] 

[4 5] 

[[ 1  2  3  4  5]
 [ 4 88  6  7  8]
 [ 9  8  7  6  5]] 

[[9 8 7 6 5]] 

[[ 1  2  3  4  5  4 88  6  7  8  9  8  7  6  5]] 



In [125]:
x1=np.array([[1,2,3],[2,3,5]])
y1=np.array([[2,5,4],[5,8,-3]])
print(x1+y1,x1-y1,x1*y1,x1/y1,'\n') #element to element arithmetic operations



[[ 3  7  7]
 [ 7 11  2]] [[-1 -3 -1]
 [-3 -5  8]] [[  2  10  12]
 [ 10  24 -15]] [[ 0.5         0.4         0.75      ]
 [ 0.4         0.375      -1.66666667]] 



In [133]:
names = np.array(['Ann','Joe','Mark'])
heights = np.array([1.5, 1.78, 1.6])
weights = np.array([65, 46, 59])
bmi=weights/heights**2
print(bmi)
print('Overweight',names[bmi>25])
print('Healthy',names[(bmi>=18.5) & (bmi<=25)])
print('Underwieght',names[(bmi<18.5)])

[28.88888889 14.51836889 23.046875  ]
Overweight ['Ann']
Healthy ['Mark']
Underwieght ['Joe']


In [134]:
print(np.dot(heights,weights)) #scalar multiplication

273.78


In [135]:
x2 = np.array([[1,2,3],[4,5,6]])
y2 = np.array([[7,8],[9,10], [11,12]])
print(np.dot(x2,y2))

[[ 58  64]
 [139 154]]


In [141]:
y2 = np.matrix([[7,8],[2,3]]) #matrix
x3 = np.array([[1,2],[4,5]])
y3 = np.array([[7,8],[2,3]])
x1 = np.asmatrix(x3)
y1 = np.asmatrix(y3)
print(y2)
print(x1)
print(y1)
print(x1*y1)#vector multiplication
print(x3*y3)#element to element

[[7 8]
 [2 3]]
[[1 2]
 [4 5]]
[[7 8]
 [2 3]]
[[11 14]
 [38 47]]
[[ 7 16]
 [ 8 15]]


In [150]:
a = np.array([(1,2,3),(4,5,6), (7,8,9)])
print(a)
print(a.cumsum()) #cumulative sum
print(a.cumsum(axis=0))#cumulative sum in row
print(a.cumsum(axis=1))#cumulative sum in column

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1  3  6 10 15 21 28 36 45]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


In [161]:
ages = np.array([34,12,37,5,13])
sorted_ages = np.sort(ages)#sorting
print(sorted_ages)
print(ages)
print(ages.argsort())#index sorting
print(ages[ages.argsort()])
persons = np.array(['Johnny','Mary','Peter','Will','Joe'])
ages = np.array([34,12,37,5,13])
heights = np.array([1.76,1.2,1.68,0.5,1.25])
sort_indices = np.argsort(ages)
print(persons[sort_indices])
print(np.sort(persons))
reverse_sort_indices = np.argsort(persons)[::-1]
print(persons[reverse_sort_indices])

[ 5 12 13 34 37]
[34 12 37  5 13]
[3 1 4 0 2]
[ 5 12 13 34 37]
['Will' 'Mary' 'Joe' 'Johnny' 'Peter']
['Joe' 'Johnny' 'Mary' 'Peter' 'Will']
['Will' 'Peter' 'Mary' 'Johnny' 'Joe']


In [163]:
list1 = [[1,2,3,4], [5,6,7,8]]
a1 = np.array(list1)
print(a1)
a2=a1
print(a2)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [168]:
a2[0][0] = 11
print(a1,a2)
a1.shape = 1,-1
print(a1,a2)

[[11  2  3  4  5  6  7  8]] [[11  2  3  4  5  6  7  8]]
[[11  2  3  4  5  6  7  8]] [[11  2  3  4  5  6  7  8]]


In [172]:
list1 = [[1,2,3,4], [5,6,7,8]]
a1 = np.array(list1)
a2 = a1.view() # creates a copy of a1 by reference; but changes
# in dimension in a1 will not affect a2
a1.shape=1,-1
print(a1)
print(a2)

[[1 2 3 4 5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [175]:
list1 = [[1,2,3,4], [5,6,7,8]]
a1 = np.array(list1)
a2 = a1.copy() # create a copy of a1 by value (deep copy)
a1[1][1]=4
print(a2)# changes is not seen in a2
print(a1)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 4 7 8]]


In [17]:
c = np.array([1, 2, np.NAN, 3, 4]) # nan cleaning
print(np.isnan(c))
print(c[~np.isnan(c)])
np.mean(c[~np.isnan(c)])

[False False  True False False]
[1. 2. 3. 4.]


2.5